version: "3"
services:
  app:
    image: python:3.7.15-alpine
    build:
       context: .
       dockerfile: Dockerfile
    working_dir: /app
    environment:
      - TZ:Asia/Shanghai
      - LANG:C.UTF-8
      - MONGODB_DATABASE: flaskdb
      - MONGODB_USERNAME: flaskuser
      - MONGODB_PASSWORD: your_mongodb_password
      - MONGODB_HOSTNAME: mongodb
    networks:
      - backend


  mongodb:
    image: mongo:6.0
    volumes:
      - mongo-data:/etc/data
    networks:
      - backend

volumes:
  mongon-data: